### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by illum1n4ti** [NykoPowered/World-Of-Warcraft-Dark-Theme-UI-Texture-Pack#7]
Hallo Nyko7

Thanks for your work .. but i found a bug in HUD and QuestFrame skins. They have some issues

Regards
Polla

**Comment by NYKO7** [comment]
Hi Polla, 

In case you have problem with questlog textures being broken when you open the map then you probably ran into a problem where you copied new files over the old ones and old broken files were not rewritten because new files doesnt have some of those files anymore, so old broken files are still in your Interface folder. In that case I recommend completely deleting old Dark Theme Texture pack files from your Interface folder and downloading new ones again and copying new files into basically empty Interface folder. 

If thats not the case I will ask you to describe the issues you found, or you can even provide screenshots too. That would help a lot. If you have HUD problems (like Unitframes, minimap, micro buttons) I will ask you for your in-game resolution too then.

Thank you for your feedback.
